### ISSUE TITLE
[Scrollable]: Next and Prev buttons are not displayed

### ISSUE THREAD

**Issue by baltruschat** [ethlete-io/ethdk#1599]
The buttons are only displayed after the first element has been switched.

Component configuration:

`<et-scrollable scrollableClass="gap-4" itemSize="full" snap renderNavigation>
      @for (competition of currentCompetitions?.items; track competition.details.id) {
            <gg-competition-card [competition]="competition" [isPublic]="true" />
      }
</et-scrollable>`

https://www.fifa.gg/organizer/german-football-association

**Comment by TomTomB** [comment]
Resolved in  cdk@[v4.10.0](https://github.com/ethlete-io/ethdk/releases/tag/%40ethlete%2Fcdk%404.10.0)
